# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

J_cpp <- function(hN, DZ, W1, W2, V, A1, A2, sigma) {
    .Call(`_functions_J_cpp`, hN, DZ, W1, W2, V, A1, A2, sigma)
}

Integ1_cpp <- function(hN, DZ2, A1, sigma) {
    .Call(`_functions_Integ1_cpp`, hN, DZ2, A1, sigma)
}

Integ2_cpp <- function(hN, DZ2, A2, sigma) {
    .Call(`_functions_Integ2_cpp`, hN, DZ2, A2, sigma)
}

Integ1_cpp_opt <- function(hN, DZ2, A1, sigma) {
    .Call(`_functions_Integ1_cpp_opt`, hN, DZ2, A1, sigma)
}

Integ2_cpp_opt <- function(hN, DZ2, A2, sigma) {
    .Call(`_functions_Integ2_cpp_opt`, hN, DZ2, A2, sigma)
}

CV1_cpp <- function(hN, DZ, DZ2, W1, W2, V, A1, A2, sigma) {
    .Call(`_functions_CV1_cpp`, hN, DZ, DZ2, W1, W2, V, A1, A2, sigma)
}

CV2_cpp <- function(hN, DZ, DZ2, W1, W2, V, A1, A2, sigma) {
    .Call(`_functions_CV2_cpp`, hN, DZ, DZ2, W1, W2, V, A1, A2, sigma)
}

