// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// J_cpp
NumericVector J_cpp(double hN, NumericMatrix DZ, NumericVector W1, NumericVector W2, NumericMatrix V, NumericVector A1, NumericVector A2, double sigma);
RcppExport SEXP _functions_J_cpp(SEXP hNSEXP, SEXP DZSEXP, SEXP W1SEXP, SEXP W2SEXP, SEXP VSEXP, SEXP A1SEXP, SEXP A2SEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type hN(hNSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type DZ(DZSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A1(A1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(J_cpp(hN, DZ, W1, W2, V, A1, A2, sigma));
    return rcpp_result_gen;
END_RCPP
}
// Integ1_cpp
double Integ1_cpp(double hN, NumericMatrix DZ2, NumericVector A1, double sigma);
RcppExport SEXP _functions_Integ1_cpp(SEXP hNSEXP, SEXP DZ2SEXP, SEXP A1SEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type hN(hNSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type DZ2(DZ2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A1(A1SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(Integ1_cpp(hN, DZ2, A1, sigma));
    return rcpp_result_gen;
END_RCPP
}
// Integ2_cpp
double Integ2_cpp(double hN, NumericMatrix DZ2, NumericVector A2, double sigma);
RcppExport SEXP _functions_Integ2_cpp(SEXP hNSEXP, SEXP DZ2SEXP, SEXP A2SEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type hN(hNSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type DZ2(DZ2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(Integ2_cpp(hN, DZ2, A2, sigma));
    return rcpp_result_gen;
END_RCPP
}
// Integ1_cpp_opt
double Integ1_cpp_opt(double hN, NumericMatrix DZ2, NumericVector A1, double sigma);
RcppExport SEXP _functions_Integ1_cpp_opt(SEXP hNSEXP, SEXP DZ2SEXP, SEXP A1SEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type hN(hNSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type DZ2(DZ2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A1(A1SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(Integ1_cpp_opt(hN, DZ2, A1, sigma));
    return rcpp_result_gen;
END_RCPP
}
// Integ2_cpp_opt
double Integ2_cpp_opt(double hN, NumericMatrix DZ2, NumericVector A2, double sigma);
RcppExport SEXP _functions_Integ2_cpp_opt(SEXP hNSEXP, SEXP DZ2SEXP, SEXP A2SEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type hN(hNSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type DZ2(DZ2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(Integ2_cpp_opt(hN, DZ2, A2, sigma));
    return rcpp_result_gen;
END_RCPP
}
// CV1_cpp
double CV1_cpp(double hN, NumericMatrix DZ, NumericMatrix DZ2, NumericVector W1, NumericVector W2, NumericMatrix V, NumericVector A1, NumericVector A2, double sigma);
RcppExport SEXP _functions_CV1_cpp(SEXP hNSEXP, SEXP DZSEXP, SEXP DZ2SEXP, SEXP W1SEXP, SEXP W2SEXP, SEXP VSEXP, SEXP A1SEXP, SEXP A2SEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type hN(hNSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type DZ(DZSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type DZ2(DZ2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A1(A1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(CV1_cpp(hN, DZ, DZ2, W1, W2, V, A1, A2, sigma));
    return rcpp_result_gen;
END_RCPP
}
// CV2_cpp
double CV2_cpp(double hN, NumericMatrix DZ, NumericMatrix DZ2, NumericVector W1, NumericVector W2, NumericMatrix V, NumericVector A1, NumericVector A2, double sigma);
RcppExport SEXP _functions_CV2_cpp(SEXP hNSEXP, SEXP DZSEXP, SEXP DZ2SEXP, SEXP W1SEXP, SEXP W2SEXP, SEXP VSEXP, SEXP A1SEXP, SEXP A2SEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type hN(hNSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type DZ(DZSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type DZ2(DZ2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A1(A1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(CV2_cpp(hN, DZ, DZ2, W1, W2, V, A1, A2, sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_functions_J_cpp", (DL_FUNC) &_functions_J_cpp, 8},
    {"_functions_Integ1_cpp", (DL_FUNC) &_functions_Integ1_cpp, 4},
    {"_functions_Integ2_cpp", (DL_FUNC) &_functions_Integ2_cpp, 4},
    {"_functions_Integ1_cpp_opt", (DL_FUNC) &_functions_Integ1_cpp_opt, 4},
    {"_functions_Integ2_cpp_opt", (DL_FUNC) &_functions_Integ2_cpp_opt, 4},
    {"_functions_CV1_cpp", (DL_FUNC) &_functions_CV1_cpp, 9},
    {"_functions_CV2_cpp", (DL_FUNC) &_functions_CV2_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_functions(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
